# frozen_string_literal: true

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'lib/brcobranca_sparkpay/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    ["describe", "context", "FactoryBot.define", "configure", "factory"]

Layout/LineLength:
  Max: 121
  Exclude:
    - 'Rakefile'