require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'lib/brcobranca_sparkpay/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    ["describe", "context", "FactoryBot.define", "configure", "factory"]