version: "3.7"

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - hemocione_local

  postgresql_db:
    image: "postgres:11.4-alpine"
    environment:
      POSTGRES_PASSWORD: passwordnotsafe
    ports:
      - "5432:5432"
    volumes:
      - hemocione_data:/var/lib/postgresql/data
    networks:
      - hemocione_local

  rails_api:
    build: .
    container_name: hemocione_api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - postgresql_db
      - redis
    volumes:
      - "../hemocione-backend:/srv/backend/"
      - "rails_api-usrlocal:/usr/local/"
    tty: true
    networks:
      - hemocione_local

volumes:
  hemocione_data:
  rails_api-usrlocal:
  react_web-usrlocal:
  redis-data:

networks:
  hemocione_local: