default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306

development:
  <<: *default
  database: hemocione
  host: maria_db
  

test:
  <<: *default
  database: hemocione_test
  host: maria_db

production:
  <<: *default
  database: hemocione
  host: <% ENV['MYSQL_HOST'] %>
