default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: hemocione_test
  username: user
  password: changeme
  host: 127.0.0.1
  port: <%= ENV['DB_PORT'] %>