development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: hemocione_mongo
      hosts:
        - mongo_db:27017
      options:
        user: <%= ENV['MONGO_USERNAME'] %>
        password: <%= ENV['MONGO_PASSWORD'] %>
  options:

test:
  clients:
    default:
      database: hemocione_mongo_test
      hosts:
        - mongo_db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
