name: Rails
on: push

jobs:
  verify:
    name: RSPEC
    runs-on: ubuntu-latest

    services:
      maria_db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
        ports: 
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

      mongo_db:
        image: mongo:4.4.4
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
          - 27017:27017

      redis:
        image: redis:5
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
          MONGO_USERNAME: root
          MONGO_PASSWORD: rootpassword
          DB_PORT: ${{ job.services.maria_db.ports[3306] }}
        run: |
          cp config/database.ci.yml config/database.yml
          cp config/mongoid.ci.yml config/mongoid.yml
          bundle exec rake db:setup

      - name: Prepare for test
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA ./cc-test-reporter before-build

      - name: Unit test with Rspec test suite
        env:
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
          MONGO_USERNAME: root
          MONGO_PASSWORD: rootpassword
          RAILS_ENV: test
        run: bundle exec rspec --format progress --profile

      - name: Report coverage
        run: GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$(git rev-parse origin/$GITHUB_HEAD_REF) ./cc-test-reporter after-build -t simplecov --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
