name: Rails
on: push

jobs:
  verify:
    name: Update Test Coverage
    runs-on: ubuntu-latest

    services:
      maria_db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

      redis:
        image: redis:5
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install

      - name: Setup test database
        env:
          DATABASE_URL: mysql2://user:changeme@localhost:3306/hemocione
          RAILS_ENV: test
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
        run: |
          bundle exec rake db:setup

      - name: Run tests
        env:
          MYSQL_ROOT_PASSWORD: changeme
          MYSQL_DATABASE: hemocione
          MYSQL_USER: user
          MYSQL_PASSWORD: changeme
          RAILS_ENV: test
        run: bundle exec rspec